name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: docker build -t fr0z3nk0/squid:latest -t fr0z3nk0/squid:$GITHUB_SHA .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push fr0z3nk0/squid